version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directories:
      - "/" # Location of package manifests
      - "/launkey"  
    schedule:
      interval: "weekly"
